---
title: "New preprint on transparency in peer-reviewed climate change research"
categories: Publication
date: 2023-12-10
bibliography: ../../bibliography/my-papers.bib
---

We're pleased to see share a new preprint, "Peer-reviewed climate change research has a transparency problem. The scientific community needs to do better" [@pollack_transparency:2024].
This effort was led by Adam Pollack at Dartmourth and evolved out of many long discussions with colleagues in climate modeling, decision science, economics, engineering, environmental policy and social science, geosciences, hydrology, law, library science, philosophy, and statistics about the role of openness, transparency, and reproducibility in climate change research.

In this article, we articulate why transparency and openness matter in climate change research.
We also sample papers in the "top" climate change journals and find that only five percent of our sample meets the minimal standard of fully open data and code required for reproducibility and replicability as defined by the National Academies of Sciences, Engineering, and Medicine.
We conclude by recognizing the challenges involved and setting commitments to improve the transparency of our own research.
We hope you will join us in these commitments and in broader discussions about the role of transparency in climate change research!

Read the abstract [here](/bibliography/publications/forthcoming/pollack_transparency_2024.qmd).