---
title: Opportunities
format:
    html:
        page-layout: full
---


We are an inclusive group driven by our intellectual curiosity and sense of purpose.
Join us to use Earth science, decision science, data science, and engineering to address critical societal challenges!


:::: {.grid}
::: {.g-col-4}
::: {.callout-tip}
## Learn more 
Read our [lab guide](https://dossgollin-lab.github.io/lab-guide/){target=_blank} to learn more about our expectations and culture.
:::
:::

::: {.g-col-4}
::: {.callout-important}
## You are welcome! 
Members of historically excluded groups and first-generation students are particularly encouraged to apply.
:::
:::

::: {.g-col-4}
::: {.callout-warning}
## Policy
We do not hire unpaid interns, except for academic credit. 
:::
:::
::::

:::: {.grid}
::: {.g-col-4}
### Undergraduates

There are no current calls but there is support for motivated undergraduates to work for pay or credit.
:::
::: {.g-col-4}
### Graduate Students

We are not recruiting graduate students to start in Spring 2025, but may have openings for Fall 2025.
All positions are funded.
:::
::: {.g-col-4}
### Postdocs

We are not actively recruiting a postdoc, but there are fellowships and flexible funds available for an outstanding candidate.
:::
::::

:::: {.grid}
::: {.g-col-4}
#### How to apply

Email James a 1-2 page research statement describing the project you would like to carry out.

:::
::: {.g-col-4}
#### How to apply

Graduate admissions are handled through a formal application to the department.
See the lab guide's [instructions for prospective graduate students](https://dossgollin-lab.github.io/lab-guide/joinus/gradadmissions.html){target=_blank}.
:::
::: {.g-col-4}
#### How to apply

If you're interested, please email a CV and 2-3 page research statement to James.

Strong candidates will have strengths in several (but not all) of the following:
Bayesian modeling; spatiotemporal statistics; computer vision; surrogate modeling; fluid dynamics; precipitation physics; Julia/Python/C programming; or nonlinear dynamics.

If you're not sure whether this describes you, email James -- be aware that studies show that researchers from historically excluded groups systematically underestimate their abilities, so please don't undersell yourself! 
:::
::::

