---
title: Bayesian Model Reveals Rising Extreme Rainfall on Gulf Coast
subtitle: A novel statistical approach predicts increased rainfall intensity and variability, highlighting climate change impacts on Gulf Coast weather patterns.
categories: Publications
date: 2025-02-05
bibliography: ../../bibliography/my-papers.bib
---

Our preprint, led by [Yuchen Lu](../../people/grad-students/yuchen-lu.qmd) and titled "Bayesian Spatiotemporal Nonstationary Model Quantifies Robust Increases in Daily Extreme Rainfall Across the Western Gulf Coast", is now live on ArXiV [@lu_spatiotemporal:2025].

## Summary

We develop a novel Bayesian hierarchical model, the Spatially Varying Covariates Model, to address the challenges of estimating nonstationary extreme precipitation probabilities.
Traditional models often assume stationarity, potentially underestimating risks due to climate change.
Our model integrates nonstationarity and regionalization, leveraging spatial statistics and extreme value theory to provide robust estimates of extreme precipitation events.
We validate our approach using daily rainfall data from the Western Gulf Coast, revealing significant increases in extreme precipitation intensity and variability, particularly around Houston and New Orleans.

Our model demonstrates superior performance compared to traditional stationary models and nonstationary models that do not incorporate spatial pooling.
Through rigorous cross-validation, we show that our estimates are well-calibrated and reliable, even at ungauged locations.
The findings indicate a 10-35% increase in extreme rainfall over the past 80 years, with the largest changes in coastal areas. 
Compared to NOAA Atlas 14, our model suggests that current guidelines may underestimate future risks, highlighting the need for updated engineering designs to account for climate change impacts.
This framework offers a practical and theoretically sound method for estimating nonstationary extreme precipitation probabilities, applicable to various regions and climate variables.


## Read More

Our paper is currently undergoing peer review, so results should be treated as preliminary.
For more details, see [here](/bibliography/publications/article/lu_spatiotemporal_2025.qmd).