---
title: "Updated Thoughts on the Guadalupe Flood"
categories: [News, Floods, Texas]
date: 2025-07-08
---

I've had a chance to read, listen, and speak with journalists and colleagues over the past day.
Here are a few points that I think are important to communicate to journalists and the public, and that I wish I'd been able to communicate more clearly.

This was, first and foremost, a **horrific tragedy**.
The pain of families who can't locate their loved ones is unfathomable.
The current focus is correctly on finding anyone who may still be alive, on supporting grieving families and communities, and on providing aid to those who have lost everything.
However, this event **also highlights systemic failures** that must be addressed to prevent future tragedies.

1. **Building in the floodway is dangerous.**
The floodway is the area where water flows fastest and deepest during a flood.
It [appears](https://www.linkedin.com/posts/ucifloodlab_its-absolutely-tragic-that-so-many-young-activity-7347421268201132033-4fTV?utm_source=share&utm_medium=member_desktop&rcm=ACoAAAr66-cBAxyypBAXNFrv8xul5KsrgSYTorA) that Camp Mystic was built in the floodway of the Guadalupe River, which is a profoundly dangerous place to build a camp for children.
In most communities, likely including Kerr County (I have not verified local regulations beyond scattered reporting), new construction or major renovations would trigger some scrutiny of flood risk, but building codes are not often applied retroactively to existing structures.
While it is *socially and financially costly* to abandon or existing structures, **safety must come first**.

1. **Need for flood alert and response systems.**
The SSPEED Center, of which I am a member, has built real-time flood forecasts for Houston, and we (along with other groups) have the capability to build a similar system for the Guadalupe River, given time, resources, and collaborators.
As my colleague Phil Bedient has eloquently [argued](https://www.houstonchronicle.com/opinion/outlook/article/texas-flash-flood-prevent-gauge-warnings-20759811.php), we need to build a real-time flood forecasting system for the Guadalupe River.

    - A critical component of this is enhancing **real-time data collection**, namely stream and rainfall gauges, to monitor floods in real time. The Upper Guadalupe River has five stream gauges along its roughly 230 mile length, and some of the gauges were not functioning during the flood. Better data collection is essential to understanding and responding to floods.
    - **The weather forecasts and warnings were generally good.** The National Weather Service issued appropriate warnings as sources below describe in detail. However, predicting the **exact magnitude and location** of extreme rainfall is inherently uncertain, especially in complex terrain like the Texas Hill Country. The National Weather Service correctly identified the risk of heavy rainfall and flash flooding, and issued appropriate and timely warnings, with certainty and accuracy increasing as the event approached.
    - Alerts without **trust and plans** do not save lives. People need to get the alerts, understand what they mean, and know what steps to take. Building a flood prediction model is a necessary, but not sufficient, step to saving 
    - There is a trade-off between **certainty and lead time**. Individuals and communities can take actions to prepare for flash floods, but these actions require time to implement. Unfortunately, the hydrology of the Guadalupe River means that the time from rain to flood can be very short. This means that if you wait until the rain has already fallen, or worse until the rivers are already rising, you can only take a very limited set of actions. On the other hand, if you take action based on forecasts, you have more time to prepare, but the forecasts are inherently uncertain and you will sometimes take action that turns out to be unnecessary.

    
I am not an expert on disaster response, communication, or the many agencies involved in flood response in this region, so I am in no position to point fingers or assign blame.
However, it is unacceptable that an advanced society can place so little value on human life that we allow events like this to occur. 
There must be **constructive accountability** to ensure that we avoid preventable tragedies like this in the future.

## Further reading

There has been a lot of excellent reporting on this horrific event.
Here are some sources that I've found especially useful:

### General Coverage

- [NY Times Coverage](https://www.nytimes.com/interactive/2025/07/07/us/texas-flooding-map-guadalupe-river.html) has generally been quite good
- Houston Chronicle: [*Camp Mystic and others hit by deadly floods were built partly in ‘extremely hazardous’ flood zones*](https://www.houstonchronicle.com/projects/2025/texas-camp-mystic-guadalupe-fema-floodplains/)
- Read (or, like me, listen to) Samantha Montano's book [*Disasterology*](https://libro.fm/audiobooks/9781488211720-disasterology)

### Meteorology and Weather Alerts

- The Eyewall: [*Making sense of the weather that led to a horrible Texas flooding tragedy, plus Tropical Storm Chantal*](https://theeyewall.com/making-sense-of-the-weather-that-led-to-a-horrible-texas-flooding-tragedy-plus-tropical-storm-chantal/)
- Andrew Dessler does a good job of [explaining](https://www.theclimatebrink.com/p/update-on-texas-flooding) the role of climate change in this event
- Marshall Shepherd [*Catastrophic flooding in Texas: Were there warnings?*](https://www.forbes.com/sites/marshallshepherd/2025/07/05/catastrophic-flooding-in-texaswere-there-warnings/) provides a deep dive into the meteorological communication
- Daniel Swain's [Bluesky Thread](https://bsky.app/profile/weatherwest.bsky.social/post/3lta4d3vfk22z) also gets into the role of early warnings, communication, and dissemination
- Texas Tribune's [*Weather warnings gave officials a 3 hour, 21 minute window to save lives in Kerr County. What happened then remains unclear.*](https://www.texastribune.org/2025/07/08/texas-weather-service-warning-kerr-county/)

### Recommendations

- My colleague (and SSPEED Center director) Phil Bedient's opinion piece in the Houston Chronicle [*Flash-flooding deaths can be prevented, says storm expert. Here’s what Texas needs to do.*](https://www.houstonchronicle.com/opinion/outlook/article/texas-flash-flood-prevent-gauge-warnings-20759811.php)
- [*Hurricane Ian is proof: The US needs a national disaster safety board*](https://thehill.com/opinion/congress-blog/3702450-hurricane-ian-is-proof-the-us-needs-a-national-disaster-safety-board/)
- [FEMA](https://www.ready.gov/floods), the [Red Cross](https://www.redcross.org/get-help/how-to-prepare-for-emergencies/types-of-emergencies/flood.html), and the [National Weather Service](https://www.weather.gov/safety/flood) all have excellent resources on flood preparedness and response that you should **print out and put on your fridge** if you live in an area prone to flooding.
