---
title: "Differential effects of climate change on average and peak demand for heating and cooling across the contiguous United States"
author:
  - Yash Vijay Amonkar
  - James Doss-Gollin
  - David J. Farnham
  - Upmanu Lall
  - Vijay Modi
date: 2023-07-07
details: ""

about:
  template: solana
  links:
    - text: 'DOI: 10.31223/X5TH5X'
      href: https://doi.org/10.31223/X5TH5X

format:
  html:
    page-layout: full
---

While most electricity systems are designed to handle peak demand during summer months, pathways to deep decarbonization generally electrify building heating, thus increasing electricity demand during winter. A key question is how climate variability and change will affect peak heating and cooling demand in an electrified future. We conduct a spatially explicit analysis of trends in temperature-based proxies of electricity demand over the past 70 years. Average annual demand for heating (cooling) decreases (increases) over most of the contiguous US. However, while climate change drives robust increases in peak cooling demand, trends in peak heating demand are generally smaller and less robust. Because the distribution of temperature exhibits a long left tail, severe cold snaps dominate the extremes of thermal demand. As building heating electrifies, system operators must account for these events to ensure reliability.