---
title: "Impact of 21st Century Climate Change on Mississippi River Basin Discharge in CESM2 Large Ensemble Projections"
author:
  - Muhammad Rezaul Haider
  - Sylvia Dee
  - James Doss-Gollin
  - Kieran Dunne
  - Samuel E. Muñoz
date: 2023-01-01
details: ""

about:
  template: solana
  links:
    - text: 'DOI: 10.2139/ssrn.4498502'
      href: https://doi.org/10.2139/ssrn.4498502
      icon: link

format:
  html:
    page-layout: full
---

The Mississippi River Basin (MRB), the fourth-largest river basin in the world, is an important corridor for hydroelectric power generation, agricultural and industrial production, and riverine transportation. Historically, the Mississippi River has experienced floods resulting in significant loss of lives and property. In a future with an intensified global hydrological cycle, the altered discharge of the river may jeopardize communities and infrastructure situated in the floodplain. This study utilizes output from the Community Earth System Model version 2 (CESM2) large ensemble simulations spanning 1930 to 2100 to quantify changes in future MRB discharge under a high greenhouse gas emissions scenario (SSP3-7.0). These simulations show that increasing precipitation trends dominate increased evapotranspiration, driving an overall increase in total discharge in the Ohio and Lower Mississippi River basins. Decreasing spring snowmelt in both the Missouri and Ohio River basins results in the reduction of spring discharge. Our results harbor implications for water resources management including increased vulnerability of the Mississippi River given projected changes in climate.