---
title: "Competing Influences of Land Use and Greenhouse Gas Emissions on Mississippi River Basin Hydroclimate Simulated Over the Last Millennium"
author:
  - Kelsey Murphy
  - Sylvia Dee
  - Samuel E. Muñoz
  - James Doss-Gollin
  - Kieran Dunne
  - Michelle O'Donnell
date: 2023-01-01
details: ""

about:
  template: solana

format:
  html:
    page-layout: full
---

The Mississippi River is an important economic corridor used for generating hydroelectric power, transporting agricultural products, and providing water for municipalities and industries. The communities, industries, and infrastructure along the Mississippi River face an uncertain future as it becomes more vulnerable to climate extremes. One of the main challenges in predicting future hydroclimate conditions in the Mississippi River basin is determining whether river discharge will increase or decrease during the 21st century. Due to the limited time coverage of the 20th century record, paleoclimate data and model simulations are used to gain a better understanding of how the basin's hydroclimate responds to external influences. In this study, we investigate how human activities during the 20th century have affected the statistics of river discharge compared to a baseline representing the last millennium. We use simulations from the Community Earth System Model Last Millennium Ensemble (CESM-LME) to assess changes in key hydroclimate variables over various time scales, ranging from monthly to centennial. By conducting simulations with both anthropogenic and natural single-forcing, we can identify the hydrological responses to each type of climate forcing separately. We also conduct full-forcing simulations to evaluate projected changes in the 21st century. The results indicate that greenhouse gas emissions and land use changes generally led to wetter conditions in the 20th century compared to the pre-industrial era. However, the 21st century is projected to have more extreme precipitation events, while the overall basin is expected to be drier compared to the 20th century. The Last Millennium simulations provide additional climate information, which improves the predictive power by expanding the pool of statistics available. Understanding the factors that contributed to past flooding events can help in developing strategies to mitigate future regional floods.