---
title: "Pluvial Flood Emulation with Hydraulics-informed Message Passing accepted to ICML 2024"
categories: Publications
date: 2024-06-09
bibliography: ../../_bibliography/my-papers.bib
---

Our paper titled "Pluvial Flood Emulation with Hydraulics-informed Message Passing" has been accepted to the 2024 International Conference on Machine Learning (ICML) [@kazadi_icml:2024].

Given a geographical region and precipitation data, our model predicts water depths in an auto-regressive fashion using a message-passing framework inspired by the conservation of momentum and mass as expressed in the shallow-water equations.
This allows the model to effectively capture the propagation of water flow, particularly during the early stages of flooding when the water is scarce.

Our empirical results, based on a dataset covering 9 regions and 7 historical precipitation events, demonstrate that our model outperforms existing baselines, providing accurate simulations even in complex topographies. 
This solution achieves accurate results using real ground elevation data.
Additionally, our model excels in predicting flood dynamics for unseen storms and watersheds, showcasing its robustness and generalization capabilities.

For more details, see [here](../../publications/conference/kazadi_icml_2024.qmd).
This is an exciting space, and we are looking forward to sharing more updates on our ongoing research in this critical area!
