---
title: "Paper on solar and wind potential during temperature extremes published in Environmental Research Letters"
categories: Publications
date: 2024-03-18
---

A new paper [@singh_potential:2024] in the journal *Environmental Research Letters* examines shows that increasing solar and wind energy capacity could help keep the lights on during widespread hot and cold spells across the U.S.
The study found that solar and wind energy potential often increases during the types of large-scale heat waves and cold snaps that drive up energy demand and can cause power outages.
While wind potential varied by region, solar potential was higher during both hot and cold extremes in nearly every part of the country.
The findings suggest that expanding renewable energy could boost grid reliability while also reducing emissions.

For more, see [the paper](/bibliography/publications/article/singh_potential_2024.qmd) or read [this Twitter thread](https://twitter.com/ClimateChirper/status/1774821916924363142).